### ISSUE TITLE
problem with push to sqlite

### ISSUE THREAD

**Issue by criewaldt** [fitnr/acris-download#1]
make downloads acris no problem, i have all 10gb of data, but when I try to push data to sqlite table using 'make sqlite' it fails with these errors:

make sqlite

> head -n1000 data/real_property_legals.csv | \
>       csvsql --tables real_property_legals --no-constraints --no-inference --db sqlite:///
> sqlite3 acris.db "CREATE INDEX real_property_legals_idx ON real_property_legals (documentid)"
> Error: no such table: main.real_property_legals
> make: **\* [sqlite_real_property_legals] Error 1

I've tried deleting acris.db and running again with the same issue. How do i fix this?

Thanks!

**Comment by fitnr** [comment]
This was a bug. I just pushed a fix, should work now.

**Comment by criewaldt** [comment]
Thanks, I appreciate the quick response! Worked like a charm.
