### ISSUE TITLE
Leading 0's stripped from Block & Lot in real_property_legals [sqlite]

### ISSUE THREAD

**Issue by criewaldt** [fitnr/acris-download#2]
block & lot values in real_property_legals seem to be missing leading 0's

**Comment by criewaldt** [comment]
Not sure if this is actually a bug or just my misunderstanding of the way the db is setup/the way lot block info is notated in acris

**Comment by fitnr** [comment]
The data from DOF doesn't have leading zeros. I think creating them would be a little presumptuous. Here's my [favorite way](http://stackoverflow.com/a/9603175/5812487) to do left padding with SQLite.

Using that method, a query to get BBLs would look like:

``` sqlite
SELECT borough || substr('00000' || block, -5, 5) || substr('0000' || lot, -4, 4)
FROM real_property_legals LIMIT 10;
```

**Comment by criewaldt** [comment]
Yeah, I realized that too. I should have investigated the issue further before immediately opening a ticket.

Also, thanks for the SQLite code, it definitely helped me as I'm new to SQLite/SQL expressions in general.
