### ISSUE TITLE
syntax error running make

### ISSUE THREAD

**Issue by xploshioOn** [fitnr/acris-download#3]
Hello, I downloaded the repo, and run "make" there are some points where I get syntax errors on the downloads and all the files are 6gb of data, not 10gb

this is the output

https://gist.github.com/xploshioOn/e6ad4ec0e90642c7d7a9fc7d5c5fcb6c

And I want to know if this is really an error and the download didn't complete or it is just a warning and 6gb are the complete files, thanks

**Comment by fitnr** [comment]
What platform are you running?

**Comment by xploshioOn** [comment]
I am on linux mint right now, just clone and run the make to download the files

**Comment by fitnr** [comment]
There's a minor `awk` syntax incompatability between OSX and Linux. Should be fixed it.

Thanks for reporting, let me know if you have any other problems.
